# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ton-swift-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TonSwift', :path => '../', :testspecs => ['Tests'] 

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"

      # Fix for CTweetNacl module error with Pusher on Xcode 26.0
      # Disable explicit module builds for Pusher and TweetNacl pods
      if ['PusherSwift', 'PusherSwiftWithEncryption', 'TweetNacl'].include?(target.name)
        config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
        # Additional settings to resolve module dependencies
        config.build_settings['SWIFT_ENABLE_INCREMENTAL_COMPILATION'] = 'NO'
        config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
      end
    end
  end
  # Additional project-level settings for all targets
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
  end
end